language: python
python:
    - 2.7
    - 3.4
# Setup anaconda
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

    - conda create -q -n pycgp-test python=$TRAVIS_PYTHON_VERSION h5py numpy scipy setuptools pip
    - source activate pycgp-test

    - pip install pytest pytest-cov
script:
    - python setup.py develop
    - py.test
