language: python
python:
    - 2.7
    - 3.4
# Setup anaconda
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda
    - conda create -q -n pycgp-test python=$TRAVIS_PYTHON_VERSION numpy scipy setuptools pip
    - source activate pycgp-test
    - pip install pytest pytest-cov
script:
    - python setup.py develop
    - py.test
